"""payments: payments, payment_status_history, journal_entries fk

Revision ID: 41d83d6154ec
Revises: 47069376f20d
Create Date: 2026-08-12 14:51:37.172024

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "41d83d6154ec"
down_revision: str | None = "47069376f20d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("debtor_account_id", sa.Uuid(), nullable=False),
        sa.Column("creditor_account_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("fx_rate_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="initiated", nullable=False),
        sa.Column("end_to_end_id", sa.String(length=35), nullable=True),
        sa.Column("version", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("amount > 0", name="ck_payments_amount_positive"),
        sa.ForeignKeyConstraint(
            ["creditor_account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["debtor_account_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "payment_status_history",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("payment_id", sa.Uuid(), nullable=False),
        sa.Column("from_status", sa.String(length=20), nullable=True),
        sa.Column("to_status", sa.String(length=20), nullable=False),
        sa.Column(
            "transitioned_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("reason", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payment_status_history_payment_id"),
        "payment_status_history",
        ["payment_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_journal_entries_payment_id_payments",
        "journal_entries",
        "payments",
        ["payment_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_journal_entries_payment_id_payments", "journal_entries", type_="foreignkey"
    )
    op.drop_index(op.f("ix_payment_status_history_payment_id"), table_name="payment_status_history")
    op.drop_table("payment_status_history")
    op.drop_table("payments")
    # ### end Alembic commands ###
