"""ledger core: accounts, journal_entries, journal_lines

Revision ID: 47069376f20d
Revises: 563ecbcbfc25
Create Date: 2026-08-12 14:40:21.485777

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "47069376f20d"
down_revision: str | None = "563ecbcbfc25"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_number", sa.String(length=34), nullable=False),
        sa.Column("owner_name", sa.String(length=255), nullable=False),
        sa.Column("account_type", sa.String(length=20), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column("version", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_number"),
    )
    op.create_table(
        "journal_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("payment_id", sa.Uuid(), nullable=True),
        sa.Column("entry_type", sa.String(length=30), nullable=False),
        sa.Column("idempotency_key_id", sa.Uuid(), nullable=True),
        sa.Column("posted_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "journal_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("journal_entry_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("direction", sa.String(length=6), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("direction IN ('debit', 'credit')", name="ck_journal_lines_direction"),
        sa.CheckConstraint("amount > 0", name="ck_journal_lines_amount_positive"),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["journal_entry_id"],
            ["journal_entries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_journal_lines_account_id"), "journal_lines", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_journal_lines_journal_entry_id"),
        "journal_lines",
        ["journal_entry_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Reporting view: balances are always derived from journal_lines, never stored. This
    # view exists for ad-hoc inspection/dashboards only — the API computes balances the
    # same way via a direct aggregate query (see SqlAlchemyLedgerRepository.get_balance).
    op.execute("""
        CREATE VIEW account_balances AS
        SELECT account_id,
               currency,
               SUM(CASE WHEN direction = 'credit' THEN amount ELSE -amount END) AS balance
        FROM journal_lines
        GROUP BY account_id, currency
    """)


def downgrade() -> None:
    op.execute("DROP VIEW account_balances")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_journal_lines_journal_entry_id"), table_name="journal_lines")
    op.drop_index(op.f("ix_journal_lines_account_id"), table_name="journal_lines")
    op.drop_table("journal_lines")
    op.drop_table("journal_entries")
    op.drop_table("accounts")
    # ### end Alembic commands ###
