"""fx rates and fx suspense account

Revision ID: 853dcecf0a07
Revises: fcc1cc4c48d7
Create Date: 2026-08-12 15:55:59.143350

"""

import uuid
from collections.abc import Sequence
from decimal import Decimal

import sqlalchemy as sa
from alembic import op

revision: str = "853dcecf0a07"
down_revision: str | None = "fcc1cc4c48d7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_ACCOUNTS_TABLE = sa.table(
    "accounts",
    sa.column("id", sa.Uuid()),
    sa.column("account_number", sa.String()),
    sa.column("owner_name", sa.String()),
    sa.column("account_type", sa.String()),
    sa.column("currency", sa.String()),
    sa.column("status", sa.String()),
    sa.column("version", sa.Integer()),
)

_FX_RATES_TABLE = sa.table(
    "fx_rates",
    sa.column("id", sa.Uuid()),
    sa.column("base_currency", sa.String()),
    sa.column("quote_currency", sa.String()),
    sa.column("rate", sa.Numeric()),
    sa.column("source", sa.String()),
)

FX_SUSPENSE_ACCOUNT_NUMBER = "FX-SUSPENSE"

# A small mock feed, not a live market connection — see docs/adr/0004-mock-fx-rate-feed.md.
_MOCK_RATES = [
    ("SGD", "USD", "0.74"),
    ("USD", "SGD", "1.35"),
    ("SGD", "EUR", "0.68"),
    ("EUR", "SGD", "1.47"),
    ("SGD", "GBP", "0.59"),
    ("GBP", "SGD", "1.69"),
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fx_rates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("base_currency", sa.String(length=3), nullable=False),
        sa.Column("quote_currency", sa.String(length=3), nullable=False),
        sa.Column("rate", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column(
            "booked_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("source", sa.String(length=50), server_default="mock-feed", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "payments", sa.Column("creditor_amount", sa.Numeric(precision=18, scale=2), nullable=True)
    )
    op.create_foreign_key(
        "fk_payments_fx_rate_id_fx_rates", "payments", "fx_rates", ["fx_rate_id"], ["id"]
    )
    # ### end Alembic commands ###

    op.bulk_insert(
        _ACCOUNTS_TABLE,
        [
            {
                "id": uuid.uuid4(),
                "account_number": FX_SUSPENSE_ACCOUNT_NUMBER,
                "owner_name": "FX Suspense",
                "account_type": "fx_suspense",
                "currency": "SGD",
                "status": "active",
                "version": 0,
            }
        ],
    )
    op.bulk_insert(
        _FX_RATES_TABLE,
        [
            {
                "id": uuid.uuid4(),
                "base_currency": base,
                "quote_currency": quote,
                "rate": Decimal(rate),
                "source": "mock-feed",
            }
            for base, quote, rate in _MOCK_RATES
        ],
    )


def downgrade() -> None:
    op.execute(f"DELETE FROM accounts WHERE account_number = '{FX_SUSPENSE_ACCOUNT_NUMBER}'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_payments_fx_rate_id_fx_rates", "payments", type_="foreignkey")
    op.drop_column("payments", "creditor_amount")
    op.drop_table("fx_rates")
    # ### end Alembic commands ###
