"""reconciliation: settlement records, runs, breaks; transitioned_at tz fix

Revision ID: fcc1cc4c48d7
Revises: 207c3d160896
Create Date: 2026-08-12 15:41:34.960552

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "fcc1cc4c48d7"
down_revision: str | None = "207c3d160896"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reconciliation_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("run_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("matched_count", sa.Integer(), nullable=False),
        sa.Column("break_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reconciliation_runs_batch_id"), "reconciliation_runs", ["batch_id"], unique=False
    )
    op.create_table(
        "settlement_file_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("external_ref", sa.String(length=100), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_line", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_settlement_file_records_batch_id"),
        "settlement_file_records",
        ["batch_id"],
        unique=False,
    )
    op.create_table(
        "reconciliation_breaks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("payment_id", sa.Uuid(), nullable=True),
        sa.Column("external_ref", sa.String(length=100), nullable=False),
        sa.Column("break_type", sa.String(length=30), nullable=False),
        sa.Column("ledger_amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("settlement_amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("details", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["reconciliation_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reconciliation_breaks_run_id"), "reconciliation_breaks", ["run_id"], unique=False
    )
    op.alter_column(
        "payment_status_history",
        "transitioned_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "payment_status_history",
        "transitioned_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_reconciliation_breaks_run_id"), table_name="reconciliation_breaks")
    op.drop_table("reconciliation_breaks")
    op.drop_index(op.f("ix_settlement_file_records_batch_id"), table_name="settlement_file_records")
    op.drop_table("settlement_file_records")
    op.drop_index(op.f("ix_reconciliation_runs_batch_id"), table_name="reconciliation_runs")
    op.drop_table("reconciliation_runs")
    # ### end Alembic commands ###
